import type { AirQualityResult, WeatherResult, EnvAlert, AlertSeverity, AlertCategory, Persona } from '../types';

/**
 * Canonical severity ranking, used to guarantee Critical alerts always
 * sort first wherever alerts are displayed (Dashboard, Warnings page,
 * Travel destination alerts) — rather than relying on the incidental
 * order these checks happen to run in below, which would silently break
 * if a new rule were ever inserted in the wrong place or a threshold
 * changed the natural firing order.
 */
const SEVERITY_RANK: Record<AlertSeverity, number> = {
  Critical: 0,
  High: 1,
  Medium: 2,
  Low: 3,
};

export function sortAlertsBySeverity(alerts: EnvAlert[]): EnvAlert[] {
  return [...alerts].sort((a, b) => SEVERITY_RANK[a.severity] - SEVERITY_RANK[b.severity]);
}

/** Which alert categories matter most to each persona — used to bring
 * persona-relevant alerts to the top without hiding the rest (everyone
 * should still be able to see every active alert; this only changes
 * ordering, e.g. a farmer sees a frost/rain Weather alert before a
 * generic Pollution one, a commuter sees Visibility before Air Quality). */
const PERSONA_ALERT_CATEGORIES: Partial<Record<Persona, AlertCategory[]>> = {
  health: ['Air Quality', 'Pollution'],
  fitness: ['Weather', 'Air Quality'],
  travel: ['Weather', 'Visibility'],
  family: ['Weather', 'Visibility'],
  agriculture: ['Weather'],
  marine: ['Weather'],
  commuter: ['Visibility', 'Weather'],
  eventPlanner: ['Weather'],
};

/**
 * Sorts alerts for display given the user's selected personas: severity
 * still governs order overall, but alerts in a category relevant to any
 * selected persona are grouped ahead of non-relevant ones (severity
 * still decides order within each group). With no personas selected,
 * this is identical to a plain severity sort.
 */
export function sortAlertsForPersonas(alerts: EnvAlert[], personas: Persona[]): EnvAlert[] {
  if (personas.length === 0) return sortAlertsBySeverity(alerts);

  const relevantCategories = new Set<AlertCategory>(
    personas.flatMap((p) => PERSONA_ALERT_CATEGORIES[p] ?? [])
  );

  return [...alerts].sort((a, b) => {
    const aRelevant = relevantCategories.has(a.category) ? 0 : 1;
    const bRelevant = relevantCategories.has(b.category) ? 0 : 1;
    if (aRelevant !== bRelevant) return aRelevant - bRelevant;
    return SEVERITY_RANK[a.severity] - SEVERITY_RANK[b.severity];
  });
}

/**
 * Alerts here are derived from configurable UI thresholds applied to
 * live data — they are NOT generated by an AI model. Each alert's
 * `cause` explains the threshold that triggered it plainly, per the
 * brief's requirement to never imply AI generation for a simple
 * threshold rule.
 */
export const ALERT_THRESHOLDS = {
  aqiHigh: 150,
  aqiCritical: 250,
  pm25Spike: 90,
  extremeHeatC: 40,
  heavyRainProbability: 75,
  strongWindKph: 45,
  lowVisibilityKm: 1,
};

export function generateAlerts(
  location: string,
  airQuality: AirQualityResult | null,
  weather: WeatherResult | null
): EnvAlert[] {
  const alerts: EnvAlert[] = [];
  const now = Date.now();

  if (airQuality?.current.aqi != null) {
    const aqi = airQuality.current.aqi;
    if (aqi >= ALERT_THRESHOLDS.aqiCritical) {
      alerts.push({
        id: `aqi-critical-${location}`,
        type: 'Hazardous Air Quality',
        category: 'Air Quality',
        severity: 'Critical',
        location,
        timestamp: now,
        description: `AQI is ${aqi}, at or above the hazardous threshold of ${ALERT_THRESHOLDS.aqiCritical}.`,
        cause: `Live AQI reading exceeded the configured critical threshold (${ALERT_THRESHOLDS.aqiCritical}).`,
        action: 'Avoid all outdoor exertion. Sensitive groups should remain indoors with air filtration if available.',
        status: 'Active',
        measurement: 'AQI',
      });
    } else if (aqi >= ALERT_THRESHOLDS.aqiHigh) {
      alerts.push({
        id: `aqi-high-${location}`,
        type: 'High AQI',
        category: 'Air Quality',
        severity: 'High',
        location,
        timestamp: now,
        description: `AQI is ${aqi}, above the unhealthy threshold of ${ALERT_THRESHOLDS.aqiHigh}.`,
        cause: `Live AQI reading exceeded the configured high threshold (${ALERT_THRESHOLDS.aqiHigh}).`,
        action: 'Reduce prolonged outdoor exertion, especially for sensitive groups.',
        status: 'Active',
        measurement: 'AQI',
      });
    }
  }

  if (airQuality?.current.pm2_5 != null && airQuality.current.pm2_5 >= ALERT_THRESHOLDS.pm25Spike) {
    alerts.push({
      id: `pm25-spike-${location}`,
      type: 'PM2.5 Spike',
      category: 'Pollution',
      severity: 'High',
      location,
      timestamp: now,
      description: `PM2.5 is ${airQuality.current.pm2_5} µg/m³, above the spike threshold of ${ALERT_THRESHOLDS.pm25Spike} µg/m³.`,
      cause: `Live PM2.5 reading exceeded the configured spike threshold (${ALERT_THRESHOLDS.pm25Spike} µg/m³).`,
      action: 'Limit outdoor activity; consider N95-grade masks for extended exposure.',
      status: 'Active',
      measurement: 'PM2.5',
    });
  }

  if (weather?.current) {
    const w = weather.current;
    if (w.temperature >= ALERT_THRESHOLDS.extremeHeatC) {
      alerts.push({
        id: `heat-${location}`,
        type: 'Extreme Heat',
        category: 'Weather',
        severity: 'High',
        location,
        timestamp: now,
        description: `Temperature is ${w.temperature}°C, at or above the extreme heat threshold of ${ALERT_THRESHOLDS.extremeHeatC}°C.`,
        cause: `Live temperature reading exceeded the configured extreme-heat threshold.`,
        action: 'Stay hydrated, avoid direct sun exposure during peak hours.',
        status: 'Active',
        measurement: 'Temperature',
      });
    }
    if (w.precipitationProbability >= ALERT_THRESHOLDS.heavyRainProbability) {
      alerts.push({
        id: `rain-${location}`,
        type: 'Heavy Rainfall Likely',
        category: 'Weather',
        severity: 'Medium',
        location,
        timestamp: now,
        description: `Precipitation probability is ${w.precipitationProbability}%, above the ${ALERT_THRESHOLDS.heavyRainProbability}% threshold.`,
        cause: 'Live forecast precipitation probability exceeded the configured threshold.',
        action: 'Plan for localized flooding risk and carry rain protection.',
        status: 'Active',
        measurement: 'Precipitation Probability',
      });
    }
    if (w.windSpeed >= ALERT_THRESHOLDS.strongWindKph) {
      alerts.push({
        id: `wind-${location}`,
        type: 'Strong Winds',
        category: 'Weather',
        severity: 'Medium',
        location,
        timestamp: now,
        description: `Wind speed is ${w.windSpeed} km/h, above the ${ALERT_THRESHOLDS.strongWindKph} km/h threshold.`,
        cause: 'Live wind speed reading exceeded the configured threshold.',
        action: 'Secure loose outdoor equipment; use caution while driving high-sided vehicles.',
        status: 'Active',
        measurement: 'Wind Speed',
      });
    }
    if (w.visibility <= ALERT_THRESHOLDS.lowVisibilityKm) {
      alerts.push({
        id: `visibility-${location}`,
        type: 'Low Visibility',
        category: 'Visibility',
        severity: 'Medium',
        location,
        timestamp: now,
        description: `Visibility is ${w.visibility} km, at or below the ${ALERT_THRESHOLDS.lowVisibilityKm} km threshold.`,
        cause: 'Live visibility reading fell below the configured threshold.',
        action: 'Reduce driving speed; allow greater following distance.',
        status: 'Active',
        measurement: 'Visibility',
      });
    }
  }

  return sortAlertsBySeverity(alerts);
}
