import { tr } from '../i18n/dynamic';
import type { AirQualityResult, WeatherResult, EnvAlert, AlertSeverity, AlertCategory, Persona } from '../types';

/**
 * Canonical severity ranking, used to guarantee Critical alerts always
 * sort first wherever alerts are displayed (Dashboard, Warnings page,
 * Travel destination alerts) — rather than relying on the incidental
 * order these checks happen to run in below, which would silently break
 * if a new rule were ever inserted in the wrong place or a threshold
 * changed the natural firing order.
 */
const SEVERITY_RANK: Record<AlertSeverity, number> = {
  Critical: 0,
  High: 1,
  Medium: 2,
  Low: 3,
};

export function sortAlertsBySeverity(alerts: EnvAlert[]): EnvAlert[] {
  return [...alerts].sort((a, b) => SEVERITY_RANK[a.severity] - SEVERITY_RANK[b.severity]);
}

/** Which alert categories matter most to each persona — used to bring
 * persona-relevant alerts to the top without hiding the rest (everyone
 * should still be able to see every active alert; this only changes
 * ordering, e.g. a farmer sees a frost/rain Weather alert before a
 * generic Pollution one, a commuter sees Visibility before Air Quality). */
const PERSONA_ALERT_CATEGORIES: Partial<Record<Persona, AlertCategory[]>> = {
  health: ['Air Quality', 'Pollution'],
  fitness: ['Weather', 'Air Quality'],
  travel: ['Weather', 'Visibility'],
  family: ['Weather', 'Visibility'],
  agriculture: ['Weather'],
  marine: ['Weather'],
  commuter: ['Visibility', 'Weather'],
  eventPlanner: ['Weather'],
};

/**
 * Sorts alerts for display given the user's selected personas: severity
 * still governs order overall, but alerts in a category relevant to any
 * selected persona are grouped ahead of non-relevant ones (severity
 * still decides order within each group). With no personas selected,
 * this is identical to a plain severity sort.
 */
export function sortAlertsForPersonas(alerts: EnvAlert[], personas: Persona[]): EnvAlert[] {
  if (personas.length === 0) return sortAlertsBySeverity(alerts);

  const relevantCategories = new Set<AlertCategory>(
    personas.flatMap((p) => PERSONA_ALERT_CATEGORIES[p] ?? [])
  );

  return [...alerts].sort((a, b) => {
    const aRelevant = relevantCategories.has(a.category) ? 0 : 1;
    const bRelevant = relevantCategories.has(b.category) ? 0 : 1;
    if (aRelevant !== bRelevant) return aRelevant - bRelevant;
    return SEVERITY_RANK[a.severity] - SEVERITY_RANK[b.severity];
  });
}

/**
 * Alerts here are derived from configurable UI thresholds applied to
 * live data — they are NOT generated by an AI model. Each alert's
 * `cause` explains the threshold that triggered it plainly, per the
 * brief's requirement to never imply AI generation for a simple
 * threshold rule.
 */
export const ALERT_THRESHOLDS = {
  aqiHigh: 150,
  aqiCritical: 250,
  pm25Spike: 90,
  extremeHeatC: 40,
  heavyRainProbability: 75,
  strongWindKph: 45,
  lowVisibilityKm: 1,
};

export function generateAlerts(
  location: string,
  airQuality: AirQualityResult | null,
  weather: WeatherResult | null
): EnvAlert[] {
  const alerts: EnvAlert[] = [];
  const now = Date.now();
  const T = ALERT_THRESHOLDS;

  if (airQuality?.current.aqi != null) {
    const aqi = airQuality.current.aqi;
    if (aqi >= T.aqiCritical) {
      alerts.push({
        id: `aqi-critical-${location}`,
        type: tr('Hazardous Air Quality', 'ख़तरनाक वायु गुणवत्ता'),
        category: 'Air Quality',
        severity: 'Critical',
        location,
        timestamp: now,
        description: tr(`AQI is ${aqi}, at or above the hazardous threshold of ${T.aqiCritical}.`, `AQI ${aqi} है, जो ${T.aqiCritical} की ख़तरनाक सीमा पर या उससे ऊपर है।`),
        cause: tr(`Live AQI reading exceeded the configured critical threshold (${T.aqiCritical}).`, `लाइव AQI रीडिंग तय की गई गंभीर सीमा (${T.aqiCritical}) से ऊपर गई।`),
        action: tr(
          'Avoid all outdoor exertion. Sensitive groups should remain indoors with air filtration if available.',
          'बाहर की हर मेहनत से बचें। संवेदनशील समूह घर के अंदर रहें, और हो सके तो एयर फ़िल्टर चलाएँ।'
        ),
        status: 'Active',
        measurement: 'AQI',
      });
    } else if (aqi >= T.aqiHigh) {
      alerts.push({
        id: `aqi-high-${location}`,
        type: tr('High AQI', 'ऊँचा AQI'),
        category: 'Air Quality',
        severity: 'High',
        location,
        timestamp: now,
        description: tr(`AQI is ${aqi}, above the unhealthy threshold of ${T.aqiHigh}.`, `AQI ${aqi} है, जो ${T.aqiHigh} की अस्वस्थ सीमा से ऊपर है।`),
        cause: tr(`Live AQI reading exceeded the configured high threshold (${T.aqiHigh}).`, `लाइव AQI रीडिंग तय की गई ऊँची सीमा (${T.aqiHigh}) से ऊपर गई।`),
        action: tr('Reduce prolonged outdoor exertion, especially for sensitive groups.', 'लंबी बाहरी मेहनत कम करें, ख़ासकर संवेदनशील समूह।'),
        status: 'Active',
        measurement: 'AQI',
      });
    }
  }

  if (airQuality?.current.pm2_5 != null && airQuality.current.pm2_5 >= T.pm25Spike) {
    const v = airQuality.current.pm2_5;
    alerts.push({
      id: `pm25-spike-${location}`,
      type: tr('PM2.5 Spike', 'PM2.5 में उछाल'),
      category: 'Pollution',
      severity: 'High',
      location,
      timestamp: now,
      description: tr(`PM2.5 is ${v} µg/m³, above the spike threshold of ${T.pm25Spike} µg/m³.`, `PM2.5 ${v} µg/m³ है, जो ${T.pm25Spike} µg/m³ की उछाल-सीमा से ऊपर है।`),
      cause: tr(`Live PM2.5 reading exceeded the configured spike threshold (${T.pm25Spike} µg/m³).`, `लाइव PM2.5 रीडिंग तय की गई उछाल-सीमा (${T.pm25Spike} µg/m³) से ऊपर गई।`),
      action: tr('Limit outdoor activity; consider N95-grade masks for extended exposure.', 'बाहरी गतिविधि सीमित करें; लंबे समय बाहर रहना हो तो N95 मास्क पहनें।'),
      status: 'Active',
      measurement: 'PM2.5',
    });
  }

  if (weather?.current) {
    const w = weather.current;
    if (w.temperature >= T.extremeHeatC) {
      alerts.push({
        id: `heat-${location}`,
        type: tr('Extreme Heat', 'भीषण गर्मी'),
        category: 'Weather',
        severity: 'High',
        location,
        timestamp: now,
        description: tr(`Temperature is ${w.temperature}°C, at or above the extreme heat threshold of ${T.extremeHeatC}°C.`, `तापमान ${w.temperature}°C है, जो ${T.extremeHeatC}°C की भीषण गर्मी की सीमा पर या उससे ऊपर है।`),
        cause: tr('Live temperature reading exceeded the configured extreme-heat threshold.', 'लाइव तापमान रीडिंग तय की गई भीषण-गर्मी सीमा से ऊपर गई।'),
        action: tr('Stay hydrated, avoid direct sun exposure during peak hours.', 'पानी पीते रहें, चरम घंटों में सीधी धूप से बचें।'),
        status: 'Active',
        measurement: 'Temperature',
      });
    }
    if (w.precipitationProbability >= T.heavyRainProbability) {
      alerts.push({
        id: `rain-${location}`,
        type: tr('Heavy Rainfall Likely', 'भारी बारिश की संभावना'),
        category: 'Weather',
        severity: 'Medium',
        location,
        timestamp: now,
        description: tr(`Precipitation probability is ${w.precipitationProbability}%, above the ${T.heavyRainProbability}% threshold.`, `वर्षा की संभावना ${w.precipitationProbability}% है, जो ${T.heavyRainProbability}% की सीमा से ऊपर है।`),
        cause: tr('Live forecast precipitation probability exceeded the configured threshold.', 'लाइव पूर्वानुमान की वर्षा-संभावना तय की गई सीमा से ऊपर गई।'),
        action: tr('Plan for localized flooding risk and carry rain protection.', 'स्थानीय जलभराव के ख़तरे को ध्यान में रखें और बारिश से बचाव साथ रखें।'),
        status: 'Active',
        measurement: 'Precipitation Probability',
      });
    }
    if (w.windSpeed >= T.strongWindKph) {
      alerts.push({
        id: `wind-${location}`,
        type: tr('Strong Winds', 'तेज़ हवाएँ'),
        category: 'Weather',
        severity: 'Medium',
        location,
        timestamp: now,
        description: tr(`Wind speed is ${w.windSpeed} km/h, above the ${T.strongWindKph} km/h threshold.`, `हवा की गति ${w.windSpeed} किमी/घं है, जो ${T.strongWindKph} किमी/घं की सीमा से ऊपर है।`),
        cause: tr('Live wind speed reading exceeded the configured threshold.', 'लाइव हवा की गति तय की गई सीमा से ऊपर गई।'),
        action: tr('Secure loose outdoor equipment; use caution while driving high-sided vehicles.', 'बाहर का ढीला सामान बाँधकर रखें; ऊँचे वाहन चलाते समय सावधानी रखें।'),
        status: 'Active',
        measurement: 'Wind Speed',
      });
    }
    if (w.visibility <= T.lowVisibilityKm) {
      alerts.push({
        id: `visibility-${location}`,
        type: tr('Low Visibility', 'कम दृश्यता'),
        category: 'Visibility',
        severity: 'Medium',
        location,
        timestamp: now,
        description: tr(`Visibility is ${w.visibility} km, at or below the ${T.lowVisibilityKm} km threshold.`, `दृश्यता ${w.visibility} किमी है, जो ${T.lowVisibilityKm} किमी की सीमा पर या उससे कम है।`),
        cause: tr('Live visibility reading fell below the configured threshold.', 'लाइव दृश्यता रीडिंग तय की गई सीमा से नीचे गई।'),
        action: tr('Reduce driving speed; allow greater following distance.', 'गाड़ी की गति कम करें; आगे वाली गाड़ी से ज़्यादा दूरी रखें।'),
        status: 'Active',
        measurement: 'Visibility',
      });
    }
  }

  return sortAlertsBySeverity(alerts);
}
